ruby/chess_site/config/routes.rb
Rails.application.routes.draw do
  resources :games

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/games/:id/play' => 'games#play', as: :play
  get '/games/:id/move/:from' => 'games#check_move'
  get '/games/:id/move/:from/:to' => 'games#move'
end

ruby/chess_site/app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :winner, :class_name => 'User'
  belongs_to :loser, :class_name => 'User'
end

ruby/chess_site/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    if !current_user
      redirect_to new_session_path
    end
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  def play
    @game = Game.find(params[:id])
    @handle = BoardHandle.new
    @cboard = eval @game.board
    @board = @handle.decompress_board @cboard
    if @game.winner != current_user
      @color = 'white'
    else
      @color = 'black'
    end
    puts @color
  end

  def check_move
    game = Game.find(params[:id])
    json = {success: true}
    if game.end_time
      json[:success] = false
      render :json => json
      return
    end
    handle = BoardHandle.new
    cboard = eval game.board
    board = handle.decompress_board cboard
    from = params[:from]
    tile=handle.get_piece from
    piece=tile.piece
    pmoves = piece.check_possible_moves.map{|c| c[0].to_s+c[1].to_s}
    json[:moves]=pmoves
    render :json => json
  end

  def move
    game = Game.find(params[:id])
    if game.end_time
      render :text => 'Game over'
      return
    end
    handle = BoardHandle.new
    cboard = eval game.board
    board = handle.decompress_board cboard
    from = params[:from]
    to = params[:to]
    # puts cboard.to_s
    tile=handle.get_piece from
    piece=tile.piece
    # handle.make_move(piece,[to[0].to_i,to[1].to_i])
    if game.winner == current_user
      color="white"
      opp_color = "black"
    else
      opp_color="white"
      color = "black"
    end
    king = handle.get_king(color)
    puts '*'*100
    puts king
    puts $Old_boards.length
    player = $Players[game.id]
    if !player
      player = Player.new(color,board,handle.get_pieces(color), king, nil, $Old_boards)
      $Players[game.id] = player
      puts player.get_statistics().length
    end
    player.set_board board
    pmoves = piece.check_possible_moves.map{|c| [c[0],c[1]]}
    cmove = [to[0].to_i,to[1].to_i]
    if !(pmoves.include?(cmove))
      puts pmoves.to_s,cmove.to_s
      puts "no"
      render :text=> 'Invalid Move'
      return
    end
    move, change = player.make_move(piece,[to[0].to_i,to[1].to_i])
    if change == true
      game.end_time = Time.now
      game.save
      player.generate_statistics player.get_boards,color,opp_color
      $Old_boards = player.get_statistics
      ::ML.write_file Rails.root.join('config/initializers','statistics2.dat'), $Old_boards
      render :text => 'Game over'
      $Players[game.id] = nil
      return
    elsif change
      puts 'need to change to '+change.class.to_s
      player.change_piece piece, change
    end
    board = player.get_board
    current_board = {board: Marshal.load(Marshal.dump(board)).dup, move: nil}
    # puts current_board
    current_board[:move] = move
    player.add_board current_board
    king = handle.get_king(opp_color)
    puts '*'*100
    opp = Player.new(opp_color,board,handle.get_pieces(opp_color), king, nil, $Old_boards)
    change = opp.play
    if change == true
      game.end_time = Time.now
      game.save
      $Old_boards = opp.get_statistics
      ::ML.write_file Rails.root.join('config/initializers','statistics2.dat'), $Old_boards
      render :text => 'Game over'
      $Players[game.id] = nil
      return
    end
    # board = opp.get_board
    # handle.set_board board
    game.board = opp.compress_board
    game.save
    render :text => 'done'
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    handle = BoardHandle.new
    handle.new_board
    bot = User.where(:bot => true).first
    @game.board = handle.compress_board
    no_players = params[:user][:no_players].to_i    
    color = params[:user][:color] 
    if no_players == 1   
      @game.start_time = Time.now
      if color == "white"
        @game.winner = current_user
        @game.loser = bot
      elsif color == "black"
        @game.winner = bot
        @game.loser = current_user
        puts 'White is gonna play'
        board = handle.decompress_board(eval @game.board)
        # board = @game.board
        opp_color = "white"
        king = handle.get_king(opp_color)
        opp = Player.new(opp_color,board,handle.get_pieces(opp_color), king, nil, $Old_boards)
        change = opp.play
        @game.board = opp.compress_board
      end
    else
      if color == "white"
        @game.winner = current_user
        @game.loser = nil
      elsif color == "black"
        @game.winner = nil
        @game.loser = current_user
      end
    end
    puts color
    @game.save
    redirect_to play_path(@game)
    # respond_to do |format|
    #   if @game.save
    #     format.html { redirect_to @game, notice: 'Game was successfully created.' }
    #     format.json { render :show, status: :created, location: @game }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @game.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:winner_id, :loser_id, :start_time, :end_time, :board, :no_players)
    end
end

ruby/chess_site/app/helpers/games_helper.rb
module GamesHelper
end

ruby/chess_site/app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%# f.association :winner %>
    <%# f.association :loser %>
    <%# f.input :start_time %>
    <%# f.input :end_time %>
    <%= f.input :board, as: :hidden %>
    <label for="user_no_players">No of Players</label><br>
    <input name="user[no_players]" value="1" class="f1orm-control" id="user_no_players" type="radio" checked>1
    <input name="user[no_players]" value="2" class="f1orm-control" id="user_no_players" type="radio">2
    <br><br>
    <label for="user_color">Color</label><br>
    <div class="col-md-6">
      <div style="margin:auto;width:200px;height:250px">
        <div style="display:inline-block;position:relative;top:100px;">
          <label for="user_color_white" style="font-weight:normal"><span class="big-piece">&#9812;</span><br><div class="text-center">White<br></div></label><div class="text-center"><input name="user[color]" value="white" class="f1orm-control hidden" id="user_color_white" type="radio" checked></div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div style="margin:auto;width:200px;height:250px">
        <div style="display:inline-block;position:relative;top:100px;">
          <label for="user_color_black" style="font-weight:normal"><span class="big-piece">&#9818;</span><br><div class="text-center">Black<br></div></label><div class="text-center"><input name="user[color]" value="black" class="f1orm-control hidden" id="user_color_black" type="radio"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit,'Start Game' %>
  </div>
<% end %>

ruby/chess_site/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

ruby/chess_site/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Winner</th>
      <th>Loser</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.winner %></td>
        <td><%= game.loser %></td>
        <td><%= game.start_time %></td>
        <td><%= game.end_time %></td>
        <td><%= game.board %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

ruby/chess_site/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

ruby/chess_site/app/views/games/play.html.erb
<h1 style="text-align:center"><%= 'Game Over' if @game.end_time %></h1>
<div class="chessboard">
	<% (1..8).each do |row| %>
		<% (1..8).each do |col| %>
			<% color = ((row+col)%2==0) ? 'white' : 'black'%>
			<div class="tile <%= color %> <%= 'clickable' if raw(@handle.html_piece @cboard[(row-1)*8+col-1]).length > 0 and @cboard[(row-1)*8+col-1][0] != @color.to_s.upcase[0]%> <%= 'opponent' if @cboard[(row-1)*8+col-1][0] == @color.to_s.upcase[0] %>" id="<%= row.to_s+col.to_s%>">&nbsp;<span class="piece" piece="<%= @cboard[(row-1)*8+col-1] %>"><%= raw(@handle.html_piece @cboard[(row-1)*8+col-1])%></span>&nbsp;</div>
		<% end %>
		<br>
	<% end %>
</div>

ruby/chess_site/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Winner:</strong>
  <%= @game.winner %>
</p>

<p>
  <strong>Loser:</strong>
  <%= @game.loser %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @game.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @game.end_time %>
</p>

<p>
  <strong>Board:</strong>
  <%= @game.board %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>